Update rbtagger

diff --git a/plugins/ruby/rbtagger/bin/ruby_index_tags b/plugins/ruby/rbtagger/bin/ruby_index_tags
--- a/plugins/ruby/rbtagger/bin/ruby_index_tags
+++ b/plugins/ruby/rbtagger/bin/ruby_index_tags
@@ -1,69 +1,164 @@
 #!/usr/bin/env bash
 set -e
 
-project_dir=${1:-.}
-gemfile="${project_dir}/Gemfile"
-temp_tags_file="${project_dir}/TAGS.$$" # Suffix with PID to make it unique
-final_tags_file="${project_dir}/TAGS"
+function current_timestamp {
+    echo $(date +%s)
+}
 
-trap '/bin/rm -f $temp_tags_file' EXIT
+project_dir=${1:-$(pwd)}
+project_name=$(basename $project_dir)
+lock_file="${project_dir}/.rbtagger-lock"
+gemfile="${project_dir}/Gemfile"
+temp_tags_file="${project_dir}/TAGS.temp"
+final_tags_file="${project_dir}/TAGS"
+lock_timeout_seconds=300 # 5 minutes
+
+function warn {
+    local message=$@
+
+    echo "$message" 1>&2
+}
 
 function abort {
-    local message=$1
+    local message=$@
 
-    echo "$message" > /dev/stderr
+    warn "$message"
     exit 1
 }
+
+function check_if_script_can_run {
+    if ! command -v gem > /dev/null; then
+        abort "Can't find gem command. Ruby doesn't seem to be installed."
+    fi
+
+    if ! ripper-tags --help > /dev/null 2>&1; then
+        echo "Installing ripper-tags gem..."
+        gem install ripper-tags
+    fi
+
+    if ! command -v bundler > /dev/null; then
+        # We don't automatically install bundler because the user might
+        # prefer a specific version.
+        abort "Can't find bundler. Make sure to gem install bundler."
+    fi
+
+    if [[ ! -f $gemfile ]]; then
+        abort "Could not generate tags. Are you in a Ruby project directory?"
+    fi
+}
+
+function cleanup {
+    rm -f "$temp_tags_file" "$lock_file"
+}
+
+function wait_on_lock {
+    local start_timestamp=$(current_timestamp)
+    local elapsed_seconds
+
+    while [[ -f "$lock_file" ]]; do
+        elapsed_seconds=$(($(current_timestamp) - $start_timestamp))
+
+        if [[ "$elapsed_seconds" -ge "$lock_timeout_seconds" ]]; then
+            abort "Timeout of ${lock_timeout_seconds} seconds exceeded!" \
+                  "If the script is not running, manually delete" \
+                  "the ${lock_file} stale lock file"
+        fi
+
+        sleep 1
+    done
+}
+
+function lock {
+    touch "$lock_file"
+}
+
 
 function index_main_project {
     local temp_tags_file=$1
 
-    index_dir --tag-file "$temp_tags_file" "$project_dir"
+    echo "Indexing main project..."
+
+    ripper_tags_wrapper --tag-file "$temp_tags_file" "$project_dir"
 }
 
-function index_dir {
+function ripper_tags_wrapper {
     if ! ripper-tags --extra=q --recursive --emacs \
          --exclude=.git "$@" > /dev/null; then
-        abort "Ripper tags failed! Is it really installed? Is the shim a valid reference to the ripper-tags script?"
+        abort "Ripper tags failed"
     fi
 }
 
 function index_project_gems {
     local temp_tags_file=$1
+    local gem_dir="$(gem environment gemdir)"
     local gem_list
+    local gem_list_cache_file="${gem_dir}/gems/gems.${project_name}"
+    local gem_tags_file="${gem_dir}/gems/TAGS"
 
-    cd "$project_dir"
-
-    if ! gem_list=$(bundle list --paths); then
+    if ! gem_list=$(bundle list --paths | grep -e "^/"); then
         abort "Command to list gems failed. Bundler returned an error."
     fi
 
+    if [[ -f "$gem_list_cache_file" ]]; then
+        if cmp <(echo "$gem_list") $gem_list_cache_file > /dev/null 2>&1; then
+            echo "Gems did not change, skipping..."
+            cat "$gem_tags_file" >> "$temp_tags_file"
+            return
+        fi
+    fi
+
+    echo "$gem_list" > "$gem_list_cache_file"
+    rm -f "$gem_tags_file" > /dev/null 2>&1
+
     for gem_dir in $gem_list; do
-        index_gem "$gem_dir" "$temp_tags_file"
+        index_dir "$gem_dir" "$gem_tags_file"
     done
-}
-
-function index_gem {
-    local gem_dir=$1
-    local temp_tags_file=$2
-    local gem_name
-
-    if is_git_dir "$gem_dir"; then
-      local gem_tags_file="${gem_dir}/.TAGS"
-    else
-      local gem_tags_file="${gem_dir}/TAGS"
-    fi
-
-    gem_name="$(basename "$gem_dir")"
-
-    if [[ ! -f $gem_tags_file ]] || should_index_git_dir "$gem_dir"; then
-        echo "Indexing ${gem_name}..."
-        index_dir --tag-file "$gem_tags_file" "$gem_dir"
-    else
-        echo "${gem_name} already indexed"
-    fi
 
     cat "$gem_tags_file" >> "$temp_tags_file"
+}
+
+function index_stdlib {
+    local temp_tags_file=$1
+    local stdlib_dir=""
+
+    for dir in $(ruby -e "puts \$LOAD_PATH"); do
+        if [[ -f "$dir/set.rb" ]]; then
+            stdlib_dir="$dir"
+            break
+        fi
+    done
+
+    if [[ -n "$stdlib_dir" ]]; then
+        index_dir "$stdlib_dir" "$temp_tags_file" "Ruby standard library"
+    else
+        echo "Ruby standard library not found!" 1>&2
+    fi
+}
+
+function index_dir {
+    local dir=$1
+    local temp_tags_file=$2
+    local name=${3:-$(basename $dir)}
+
+    if [[ ! -d "$dir" ]]; then
+        warn "${name} not found"
+        return
+    fi
+
+    if is_git_dir "$dir"; then
+        local tags_file="${dir}/.TAGS"
+    else
+        local tags_file="${dir}/TAGS"
+    fi
+
+    if [[ ! -f $tags_file ]] || should_index_git_dir "$dir"; then
+        echo "Indexing ${name}..."
+        ripper_tags_wrapper --tag-file "$tags_file" "$dir"
+    else
+        echo "${name} already indexed"
+    fi
+
+    cat "$tags_file" >> "$temp_tags_file"
 }
 
 function is_git_dir {
@@ -79,7 +174,7 @@ function should_index_git_dir {
     local gem_dir=$1
 
     if ! is_git_dir "$gem_dir"; then
-      return 1
+        return 1
     fi
 
     local commit_hash_file="${gem_dir}/.ruby_tags_commit_hash"
@@ -99,28 +194,14 @@ function should_index_git_dir {
     fi
 }
 
-if ! command -v gem > /dev/null; then
-    abort "Can't find gem command. Ruby doesn't seem to be installed."
-fi
+check_if_script_can_run
+wait_on_lock
+lock
 
-if ! command -v ripper-tags > /dev/null; then
-    echo "Installing ripper-tags gem..."
-    gem install ripper-tags
-fi
-
-if ! command -v bundler > /dev/null; then
-    # We don't automatically install bundler because the user might
-    # prefer a specific version.
-    abort "Can't find bundler. Make sure to gem install bundler."
-fi
-
-if [[ ! -f $gemfile ]]; then
-    abort "Could not generate tags. Are you in a Ruby project directory?"
-fi
-
-echo "Indexing main project..."
+trap "cleanup" EXIT
 
 index_main_project "$temp_tags_file"
+index_stdlib "$temp_tags_file"
 index_project_gems "$temp_tags_file"
 
 mv "$temp_tags_file" "$final_tags_file"
